Repository ThalesGroup/GeoView, pull requests merged in 2025-05, with the labels that each got.

#54 Dev brendan
  src/GeoView-Examples/GeoViewExamples.class.st
  src/GeoView/GeoMapSurface.class.st
  src/GeoView/GeoMapTile.class.st
  src/GeoView/GeoViewAbstractElement.class.st
  src/GeoView/GeoViewDefaultInteractionsStrategy.class.st
  src/GeoView/GeoViewMapTilesLayer.class.st
  src/GeoView/GeoViewProjectionChanges.class.st
Labels: bug, enhancement

#60 Rewrite CI and Readme + fix #59
  .github/workflows/CI.yml
  .github/workflows/Pharo12CI.yml
  .smalltalkci.default.ston
  README.md
Labels: technical work

#61 Create two separated baseline for GeoView and GeoView+Molecule
  .github/workflows/CI.yml
  .smalltalkci.core.ston
  README.md
  src/BaselineOfGeoView/BaselineOfGeoView.class.st
  src/BaselineOfGeoView/ManifestBaselineOfGeoView.class.st
Labels: technical work, ci/cd

#57 Tiles provider refactoring, add Google provider.
  src/GeoView-Examples/GeoViewExamples.class.st
  src/GeoView/GeoViewGoogleTilesProvider.class.st
  src/GeoView/GeoViewLocalDirectoryTilesProvider.class.st
  src/GeoView/GeoViewMapTilesLayer.class.st
  src/GeoView/GeoViewOpenStreetMapTilesProvider.class.st
  src/GeoView/GeoViewTilesProvider.class.st
  src/GeoView/GeoViewUtils.class.st
Labels: enhancement, technical work

#56 55 create map layer
  src/GeoView-Examples/GeoViewExamples.class.st
  src/GeoView/GeoMapSurface.class.st
  src/GeoView/GeoMapTile.class.st
  src/GeoView/GeoViewAbstractElement.class.st
  src/GeoView/GeoViewDefaultInteractionsStrategy.class.st
  src/GeoView/GeoViewGoogleTilesProvider.class.st
  src/GeoView/GeoViewLocalDirectoryTilesProvider.class.st
  src/GeoView/GeoViewMapTilesLayer.class.st
  src/GeoView/GeoViewOpenStreetMapTilesProvider.class.st
  src/GeoView/GeoViewProjectionChanges.class.st
  src/GeoView/GeoViewTilesProvider.class.st
  src/GeoView/GeoViewUtils.class.st
Labels: enhancement, technical work

#71 Merge brendan
  src/GeoView-Examples/GeoViewExamples.class.st
  src/GeoView-Tests/GeoViewAbstractElementTest.class.st
  src/GeoView/GeoMapSurface.class.st
  src/GeoView/GeoMapTile.class.st
  src/GeoView/GeoViewAbstractElement.class.st
  src/GeoView/GeoViewInteractionsStrategy.class.st
  src/GeoView/GeoViewMapTilesLayer.class.st
  src/GeoView/GeoViewProjectionChanges.class.st
Labels: bug, technical work

#73 Working on symbology update
  src/GeoView-Molecule/GeoViewManager.trait.st
  src/GeoView-Molecule/GeoViewManagerImpl.class.st
  src/GeoView/AbstractGeoViewGraphicModelLayer.class.st
  src/GeoView/GeoViewAbstractElement.class.st
  src/GeoView/GeoViewDShapesLayer.class.st
  src/GeoView/GeoViewDomainObjectsLayer.class.st
  src/GeoView/GeoViewMapTilesLayer.class.st
  src/GeoView/GeoViewProjectionChanges.class.st
  src/GeoView/GeoViewSymbologyChanges.class.st
  src/GeoView/GeoViewUpdateContext.class.st
Labels: enhancement
